### ISSUE TITLE
xml-crypto findattr does not handle null check well

### ISSUE THREAD

**Issue by mayhs19** [node-saml/xml-crypto#110]
xml-crypto doesnt seem to handle null checks well 
For example , for this function findattr under utils.js , `node.attributes.length` is used without checking if `node.attributes` is undefined.
[https://github.com/yaronn/xml-crypto/blob/c19bcba71b6c7191756c56ae6d1637794bade3a4/lib/utils.js#L4](url)

There might be other places that have this issue but I have come across this one for my application.Would be great if this is handled gracefully at all possible places.

**Comment by jonfairbanks** [comment]
Seconding this comment. The lack of null checks in xml-crypto causes our application to crash hard in rare circumstances. Would be great to see some additional error handling added in.

**Comment by yaronn** [comment]
Thanks @mayhs19 for alerting on this, I will fix this issue. @jonfairbanks - can you send me stack traces of crashes so I can make make sure to include them in the fix?

**Comment by jonfairbanks** [comment]
We're not using xml-crypto directly, but it is a dependency a few layers down. Most of the time this code works flawlessly but in rare occasions, we see this:

`TypeError: Cannot read property 'length' of undefined
   at Object.findAttr (/apps/snap/snapnodeweb/node_modules/xml-crypto/lib/utils.js:5:36)
   at SignedXml.loadReference (/apps/snap/snapnodeweb/node_modules/xml-crypto/lib/signed-xml.js:318:29)
   at SignedXml.loadSignature (/apps/snap/snapnodeweb/node_modules/xml-crypto/lib/signed-xml.js:280:10)
   at SAML.validateSignature (/apps/snap/snapnodeweb/node_modules/passport-saml-encrypted/lib/saml.js:236:7)
   at SAML.validateResponse (/apps/snap/snapnodeweb/node_modules/passport-saml-encrypted/lib/saml.js:255:33)
   at Strategy.authenticate (/apps/snap/snapnodeweb/node_modules/passport-saml-encrypted/lib/strategy.js:31:16)
   at attempt (/apps/snap/snapnodeweb/node_modules/passport/lib/middleware/authenticate.js:341:16)
   at authenticate (/apps/snap/snapnodeweb/node_modules/passport/lib/middleware/authenticate.js:342:7)
   at Layer.handle [as handle_request] (/apps/snap/snapnodeweb/node_modules/express/lib/router/layer.js:95:5)
   at next (/apps/snap/snapnodeweb/node_modules/express/lib/router/route.js:131:13)
   at Route.dispatch (/apps/snap/snapnodeweb/node_modules/express/lib/router/route.js:112:3)
   at Layer.handle [as handle_request] (/apps/snap/snapnodeweb/node_modules/express/lib/router/layer.js:95:5)
   at /apps/snap/snapnodeweb/node_modules/express/lib/router/index.js:277:22
   at Function.process_params (/apps/snap/snapnodeweb/node_modules/express/lib/router/index.js:330:12)
   at next (/apps/snap/snapnodeweb/node_modules/express/lib/router/index.js:271:10)
   at ssoAuthenticate (/apps/snap/snapnodeweb/node_modules/sso-paypal/lib/middleware.js:15:13)`

I added some try/catch logic [here](https://github.com/jonfairbanks/xml-crypto/commits/master) and am happy to open a pull request, but it was a quick and dirty attempt. You may have a better method in mind. 

Thanks for reviewing!

**Comment by cjbarth** [comment]
@jonfairbanks , we'd love to see a PR to address your issue and help you not have to maintain a fork. Please create a PR with a test suite and we'll take a look.

**Comment by cjbarth** [comment]
Since #388 (5.0.0), `findChildren` returns only element nodes, and those are what the internal callers pass to `findAttr`. With 6.3.2, a `Reference` whose `DigestMethod` is missing, or is only text or a comment, is rejected with `could not find DigestMethod in reference ...` rather than a `TypeError`. `findAttr` is also deprecated as a public export (#567) and will be removed in 7.0 (#551).

If you still hit a `TypeError` from xml-crypto on 6.3.2 or later, please comment here with the input and we'll reopen.
