### ISSUE TITLE
Error: error:0909006C:PEM routines:get_name:no start line

### ISSUE THREAD

**Issue by git-nikhilbhardwaj** [node-saml/xml-crypto#186]
Error: error:0909006C:PEM routines:get_name:no start line
    at Sign.sign (internal/crypto/sig.js:80:26)
    at RSASHA1.getSignature (e:\nodejs-projects\hello-worlds\node_modules\xml-crypto\lib\signed-xml.js:91:22)
    at SignedXml.calculateSignatureValue (e:\nodejs-projects\hello-worlds\node_modules\xml-crypto\lib\signed-xml.js:414:32)
    at SignedXml.computeSignature (e:\nodejs-projects\hello-worlds\node_modules\xml-crypto\lib\signed-xml.js:738:8)
    at otpRequest (e:\nodejs-projects\hello-worlds\index.js:89:6)
    at Layer.handle [as handle_request] (e:\nodejs-projects\hello-worlds\node_modules\express\lib\router\layer.js:95:5)
    at next (e:\nodejs-projects\hello-worlds\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (e:\nodejs-projects\hello-worlds\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (e:\nodejs-projects\hello-worlds\node_modules\express\lib\router\layer.js:95:5)
    at e:\nodejs-projects\hello-worlds\node_modules\express\lib\router\index.js:281:22

**Comment by mcorossigo** [comment]
Hello @yaronn 

I am experiencing this error too and it's driving me crazy. While I don't expect that you trouble shoot stuff for me, can you give me an hint about what may be wrong? Thank you!

**Comment by jasonhjohnson** [comment]
@git-nikhilbhardwaj @mcorossigo I'm having the same issue. Did you ever resolve it?

**Comment by cjbarth** [comment]
@git-nikhilbhardwaj , @mcorossigo , @jasonhjohnson , could any of you please provide version numbers and example code of your problem? Even better would be a PR with a test that fails.
